// Code generated by "stringer -type Code"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[Halt-1]
	_ = x[NegByte-2]
	_ = x[NegInt-3]
	_ = x[NegLong-4]
	_ = x[Not-5]
	_ = x[MulByte-6]
	_ = x[MulInt-7]
	_ = x[MulLong-8]
	_ = x[DivByte-9]
	_ = x[DivInt-10]
	_ = x[DivLong-11]
	_ = x[ModByte-12]
	_ = x[ModInt-13]
	_ = x[ModLong-14]
	_ = x[AddByte-15]
	_ = x[AddInt-16]
	_ = x[AddLong-17]
	_ = x[SubByte-18]
	_ = x[SubInt-19]
	_ = x[SubLong-20]
	_ = x[IfEqZero-21]
	_ = x[IfNotEqZero-22]
	_ = x[IfLessZero-23]
	_ = x[IfLessEqZero-24]
	_ = x[IfGtZero-25]
	_ = x[IfGtEqZero-26]
	_ = x[IfEq-27]
	_ = x[IfNotEq-28]
	_ = x[IfLess-29]
	_ = x[IfLessEq-30]
	_ = x[IfGt-31]
	_ = x[IfGtEq-32]
	_ = x[And-33]
	_ = x[Or-34]
	_ = x[Xor-35]
	_ = x[PushByte-36]
	_ = x[PushInt-37]
	_ = x[PushLong-38]
	_ = x[PushReference-39]
	_ = x[StoreByte-40]
	_ = x[StoreInt-41]
	_ = x[StoreLong-42]
	_ = x[StoreReference-43]
	_ = x[FetchByte-44]
	_ = x[FetchInt-45]
	_ = x[FetchLong-46]
	_ = x[FetchReference-47]
}

const _Code_name = "NopHaltNegByteNegIntNegLongNotMulByteMulIntMulLongDivByteDivIntDivLongModByteModIntModLongAddByteAddIntAddLongSubByteSubIntSubLongIfEqZeroIfNotEqZeroIfLessZeroIfLessEqZeroIfGtZeroIfGtEqZeroIfEqIfNotEqIfLessIfLessEqIfGtIfGtEqAndOrXorPushBytePushIntPushLongPushReferenceStoreByteStoreIntStoreLongStoreReferenceFetchByteFetchIntFetchLongFetchReference"

var _Code_index = [...]uint16{0, 3, 7, 14, 20, 27, 30, 37, 43, 50, 57, 63, 70, 77, 83, 90, 97, 103, 110, 117, 123, 130, 138, 149, 159, 171, 179, 189, 193, 200, 206, 214, 218, 224, 227, 229, 232, 240, 247, 255, 268, 277, 285, 294, 308, 317, 325, 334, 348}

func (i Code) String() string {
	if i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
